openapi: '3.0.3'
info:
  title: Ultradian API
  version: '1.0'
servers:
  - url: http://localhost:5000/api/
    description: Local development server
paths:
  /users:
    get:
      summary: Get all users
      description: Retrieve a list of all users in the system.
      responses:
        '200':
          description: OK
