"""future changes

Revision ID: 1255e7505648
Revises: 70bb8c0be021
Create Date: 2025-06-15 07:31:07.436185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1255e7505648'
down_revision = '70bb8c0be021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
