"""empty message

Revision ID: 4661f7658564
Revises: 7a1ac9252fd1
Create Date: 2025-06-26 12:39:13.775141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4661f7658564'
down_revision = '7a1ac9252fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
