"""empty message

Revision ID: 630323482c72
Revises: 71ffb563e8bc
Create Date: 2025-06-26 12:36:42.991180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630323482c72'
down_revision = '71ffb563e8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('peak_duration', sa.Integer(), nullable=True),
    sa.Column('trough_duration', sa.Integer(), nullable=True),
    sa.Column('morning_grog', sa.Integer(), nullable=True),
    sa.Column('cycles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_daily_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('wake_time', sa.Time(), nullable=False),
    sa.Column('hrv', sa.Integer(), nullable=True),
    sa.Column('rhr', sa.Integer(), nullable=True),
    sa.Column('sleep_duration', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_cycle_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_daily_record_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_daily_record_id'], ['user_daily_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cycle_event')
    op.drop_table('user_daily_record')
    op.drop_table('user')
    op.drop_table('leads')
    # ### end Alembic commands ###
