"""empty message

Revision ID: 71ffb563e8bc
Revises: f9051794081e
Create Date: 2025-06-26 12:19:47.709221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ffb563e8bc'
down_revision = 'f9051794081e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_daily_record')
    op.drop_table('user_cycle_event')
    op.drop_table('leads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_cycle_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_daily_record_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_daily_record_id'], ['user_daily_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_daily_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('wake_time', sa.TIME(), nullable=False),
    sa.Column('hrv', sa.FLOAT(), nullable=True),
    sa.Column('rhr', sa.FLOAT(), nullable=True),
    sa.Column('sleep_duration', sa.FLOAT(), nullable=True),
    sa.Column('mood', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('morning_grog', sa.INTEGER(), nullable=True),
    sa.Column('peak_duration', sa.INTEGER(), nullable=True),
    sa.Column('trough_duration', sa.INTEGER(), nullable=True),
    sa.Column('cycles', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
