"""add ended_at to daily record

Revision ID: 9ce8ab374ede
Revises: 18d91a416bd8
Create Date: 2025-07-11 08:36:06.943834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce8ab374ede'
down_revision = '18d91a416bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_record', schema=None) as batch_op:
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###
