"""empty message

Revision ID: f9051794081e
Revises: 82e0706d2693
Create Date: 2025-06-26 07:52:01.959858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9051794081e'
down_revision = '82e0706d2693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rhr', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sleep_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_record', schema=None) as batch_op:
        batch_op.drop_column('mood')
        batch_op.drop_column('sleep_duration')
        batch_op.drop_column('rhr')

    # ### end Alembic commands ###
